/* 
Some of the tests for the quiz controller is generated by AI, using microsoft copilot. 
All AI generated tests have been looked over and modified.
The main purpose of using AI, was primarly to test multiple functions, and as many of the test are very alike -
AI was used to avoid repetive time consuming coding, while stilling testing various functions.
The main CRUD operations of the quiz entity all have both positive and negative tests
*/

using api.Controllers;
using api.Models;
using api.DAL;
using api.DTOs;
using Moq;
using Xunit;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Microsoft.AspNetCore.Http;
using System.Security.Claims;
using System.Reflection;

namespace api.Tests.Controllers;

public class QuizControllerTests
{
    private readonly Mock<IQuizRepository> _mockRepo;
    private readonly Mock<ILogger<QuizController>> _mockLogger;
    private readonly QuizController _controller;

    public QuizControllerTests()
    {
        _mockRepo = new Mock<IQuizRepository>();
        _mockLogger = new Mock<ILogger<QuizController>>();
        _controller = new QuizController(_mockLogger.Object, _mockRepo.Object);
    }
    #region Helper Methods

    // Helper method to set up authenticated user
    private void SetupAuthenticatedUser(string userId, string role = "User")
    {
        var claims = new List<Claim>
        {
            new Claim(ClaimTypes.NameIdentifier, userId),
            new Claim(ClaimTypes.Role, role)
        };
        
        var identity = new ClaimsIdentity(claims, "TestAuthType");
        var claimsPrincipal = new ClaimsPrincipal(identity);

        _controller.ControllerContext = new ControllerContext
        {
            HttpContext = new DefaultHttpContext { User = claimsPrincipal }
        };
    }

    // Helper method to set up unauthenticated user (null ClaimsPrincipal with empty HttpContext)
    private void SetupUnauthenticatedUser()
    {
        var claimsPrincipal = new ClaimsPrincipal(); // Empty principal, no claims

        _controller.ControllerContext = new ControllerContext
        {
            HttpContext = new DefaultHttpContext { User = claimsPrincipal }
        };
    }

    #endregion

    #region GetQuizzes Tests

    [Fact]
    public async Task GetQuizzes_ok()
    {
        // arrange
        var quizzes = new List<Quiz>
        {
            new Quiz
            {
                Id = 1,
                Title = "Math Quiz",
                Description = "Basic math questions",
                UserId = "user123",
                Creator = new AuthUser { UserName = "TestUser" },
                Questions = new List<Question>
                {
                    new Question { Id = 1, QuestionText = "What is 2+2?" }
                }
            },
            new Quiz
            {
                Id = 2,
                Title = "Science Quiz",
                Description = "Basic science",
                UserId = "user456",
                Creator = new AuthUser { UserName = "ScienceUser" },
                Questions = new List<Question>
                {
                    new Question { Id = 2, QuestionText = "What is H2O?" }
                }
            }
        };

        _mockRepo.Setup(repo => repo.GetQuizzes()).ReturnsAsync(quizzes);

        // Act
        var result = await _controller.GetQuizzes();

        // Assert
        var viewResult = Assert.IsType<OkObjectResult>(result);
        Assert.NotNull(viewResult.Value);
    }

    [Fact]
    public async Task GetQuizzes_NoQuizzes()
    {
        // Arrange
        _mockRepo.Setup(repo => repo.GetQuizzes()).ReturnsAsync(new List<Quiz>());

        // Act
        var result = await _controller.GetQuizzes();

        // Assert
        var okResult = Assert.IsType<OkObjectResult>(result);
        Assert.NotNull(okResult.Value);
    }

    [Fact]
    public async Task GetQuizzes_Exception()
    {
        // Arrange
        _mockRepo.Setup(repo => repo.GetQuizzes()).ThrowsAsync(new Exception("Database error"));

        // Act
        var result = await _controller.GetQuizzes();

        // Assert
        var statusResult = Assert.IsType<ObjectResult>(result);
        Assert.Equal(500, statusResult.StatusCode);
    }

    #endregion

    #region GetQuiz Tests

    [Fact]
    public async Task GetQuiz_ok()
    {
        // mock data for quiz
        var quiz = new Quiz
        {
            Id = 1,
            Title = "Test Quiz",
            Questions = new List<Question>
            {
                new Question
                {
                    Id = 1,
                    QuestionText = "Question 1",
                    Points = 10,
                    Answers = new List<Answer>
                    {
                        new Answer { Id = 1, AnswerText = "Answer 1", IsCorrect = true },
                        new Answer { Id = 2, AnswerText = "Answer 2", IsCorrect = false }
                    }
                }
            }
        };

        _mockRepo.Setup(repo => repo.GetQuizById(1)).ReturnsAsync(quiz);

        // Act
        var result = await _controller.GetQuiz(1);

        // Assert
        var okResult = Assert.IsType<OkObjectResult>(result);
        Assert.NotNull(okResult.Value);
    }

    [Fact]
    public async Task GetQuiz_WhenIt_DoesNotExist()
    {
        // Arrange
        _mockRepo.Setup(repo => repo.GetQuizById(-1)).ReturnsAsync((Quiz?)null);

        // Act
        var result = await _controller.GetQuiz(-1);

        // Assert
        Assert.IsType<NotFoundObjectResult>(result);
    }

    [Fact]
    public async Task GetQuiz_Exception()
    {
        // Arrange
        _mockRepo.Setup(repo => repo.GetQuizById(1)).ThrowsAsync(new Exception("Database error"));

        // Act
        var result = await _controller.GetQuiz(1);

        // Assert
        var statusResult = Assert.IsType<ObjectResult>(result);
        Assert.Equal(500, statusResult.StatusCode);
    }

    #endregion

    #region CreateQuiz Tests

    [Fact]
    public async Task CreateQuiz_ok()
    {
        // Arrange
        SetupAuthenticatedUser("user123");
        var quizDto = new QuizCreationDto
        {
            Title = "New Quiz",
            Description = "Test Description",
            Questions = new List<QuestionCreationDto>
            {
                new QuestionCreationDto
                {
                    QuestionText = "Question 1",
                    Points = 10,
                    Answers = new List<AnswerCreationDto>
                    {
                        new AnswerCreationDto { AnswerText = "Answer 1", IsCorrect = true },
                        new AnswerCreationDto { AnswerText = "Answer 2", IsCorrect = false }
                    }
                }
            }
        };

        var createdQuiz = new Quiz { Id = 1, Title = "New Quiz", UserId = "user123" };
        _mockRepo.Setup(repo => repo.CreateQuiz(It.IsAny<QuizCreationDto>(), "user123")).ReturnsAsync(createdQuiz);

        // Act
        var result = await _controller.CreateQuiz(quizDto);

        // Assert
        var okResult = Assert.IsType<OkObjectResult>(result);
        Assert.NotNull(okResult.Value);
    }

    [Fact]
    public async Task CreateQuiz_Unauthorized()
    {
        // Arrange - Setup empty user
        SetupUnauthenticatedUser();
        var quizDto = new QuizCreationDto
        {
            Title = "New Quiz",
            Description = "Test",
            Questions = new List<QuestionCreationDto>
            {
                new QuestionCreationDto
                {
                    QuestionText = "Q1",
                    Answers = new List<AnswerCreationDto>
                    {
                        new AnswerCreationDto { AnswerText = "A1", IsCorrect = true }
                    }
                }
            }
        };

        // Act
        var result = await _controller.CreateQuiz(quizDto);

        // Assert
        Assert.IsType<UnauthorizedObjectResult>(result);
    }

    [Fact]
    public async Task CreateQuiz_BadRequest()
    {
        // Arrange
        SetupAuthenticatedUser("user123");
        var quizDto = new QuizCreationDto
        {
            Title = "Invalid Quiz",
            Description = "No questions",
            Questions = new List<QuestionCreationDto>()
        };

        // Act
        var result = await _controller.CreateQuiz(quizDto);

        // Assert
        Assert.IsType<BadRequestObjectResult>(result);
    }

    [Fact]
    public async Task CreateQuiz_Error()
    {
        // Arrange
        SetupAuthenticatedUser("user123");
        var quizDto = new QuizCreationDto
        {
            Title = "Test Quiz",
            Description = "Test",
            Questions = new List<QuestionCreationDto>
            {
                new QuestionCreationDto
                {
                    QuestionText = "Q1",
                    Answers = new List<AnswerCreationDto>
                    {
                        new AnswerCreationDto { AnswerText = "A1", IsCorrect = true }
                    }
                }
            }
        };

        _mockRepo.Setup(repo => repo.CreateQuiz(It.IsAny<QuizCreationDto>(), "user123"))
            .ThrowsAsync(new Exception("Database error"));

        // Act
        var result = await _controller.CreateQuiz(quizDto);

        // Assert
        var statusResult = Assert.IsType<ObjectResult>(result);
        Assert.Equal(500, statusResult.StatusCode);
    }

    #endregion

    #region UpdateQuiz Tests

    [Fact]
    public async Task UpdateQuiz_ok()
    {
        // Arrange
        SetupAuthenticatedUser("user123");
        var quizDto = new QuizCreationDto
        {
            Title = "Updated Quiz",
            Description = "Updated Description",
            Questions = new List<QuestionCreationDto>
            {
                new QuestionCreationDto
                {
                    QuestionText = "Updated Question",
                    Points = 15,
                    Answers = new List<AnswerCreationDto>
                    {
                        new AnswerCreationDto { AnswerText = "Answer 1", IsCorrect = true },
                        new AnswerCreationDto { AnswerText = "Answer 2", IsCorrect = false }
                    }
                }
            }
        };

        var updatedQuiz = new Quiz { Id = 1, Title = "Updated Quiz", UserId = "user123" };
        _mockRepo.Setup(repo => repo.UpdateQuiz(1, It.IsAny<QuizCreationDto>(), "user123")).ReturnsAsync(updatedQuiz);

        // Act
        var result = await _controller.UpdateQuiz(1, quizDto);

        // Assert
        var okResult = Assert.IsType<OkObjectResult>(result);
        Assert.NotNull(okResult.Value);
    }

    [Fact]
    public async Task UpdateQuiz_NoUser()
    {
        // Arrange - Setup empty user
        SetupUnauthenticatedUser();
        var quizDto = new QuizCreationDto
        {
            Title = "Quiz",
            Description = "Test",
            Questions = new List<QuestionCreationDto>
            {
                new QuestionCreationDto
                {
                    QuestionText = "Q1",
                    Answers = new List<AnswerCreationDto>
                    {
                        new AnswerCreationDto { AnswerText = "A1", IsCorrect = true }
                    }
                }
            }
        };

        // Act
        var result = await _controller.UpdateQuiz(1, quizDto);

        // Assert
        Assert.IsType<UnauthorizedObjectResult>(result);
    }

    [Fact]
    public async Task UpdateQuiz_BadData()
    {
        // Arrange
        SetupAuthenticatedUser("user123");
        var quizDto = new QuizCreationDto
        {
            Title = "Invalid Quiz",
            Description = "No questions",
            Questions = new List<QuestionCreationDto>()
        };

        // Act
        var result = await _controller.UpdateQuiz(1, quizDto);

        // Assert
        Assert.IsType<BadRequestObjectResult>(result);
    }

    #endregion

    #region DeleteQuiz Tests

    [Fact]
    public async Task DeleteQuiz_Successfull()
    {
        // Arrange
        SetupAuthenticatedUser("user123", "Admin"); // Add role

        var mockQuiz = new Quiz
        {
            Id = 1,
            UserId = "user123",
            Title = "Test Quiz",
            Questions = new List<Question>()
        };

        _mockRepo.Setup(repo => repo.GetQuizById(1)).ReturnsAsync(mockQuiz);
        _mockRepo.Setup(repo => repo.DeleteQuiz(1)).ReturnsAsync(true);

        // Act
        var result = await _controller.DeleteQuiz(1);

        // Assert
        Assert.IsType<NoContentResult>(result);
    }

    [Fact]
    public async Task DeleteQuiz_Error()
    {
        // Arrange
        SetupAuthenticatedUser("user123", "Admin"); // Add role

        var mockQuiz = new Quiz
        {
            Id = 1,
            UserId = "user123",
            Title = "Test Quiz",
            Questions = new List<Question>()
        };

        _mockRepo.Setup(repo => repo.GetQuizById(1)).ReturnsAsync(mockQuiz);
        _mockRepo.Setup(repo => repo.DeleteQuiz(1)).ThrowsAsync(new Exception("Database error"));

        // Act
        var result = await _controller.DeleteQuiz(1);

        // Assert
        var statusResult = Assert.IsType<ObjectResult>(result);
        Assert.Equal(500, statusResult.StatusCode);
    }

    [Fact]
    public async Task DeleteQuiz_NotFound_ReturnsNotFound()
    {
        // Arrange
        SetupAuthenticatedUser("user123");
        _mockRepo.Setup(repo => repo.GetQuizById(1)).ReturnsAsync((Quiz?)null);

        // Act
        var result = await _controller.DeleteQuiz(1);

        // Assert
        Assert.IsType<NotFoundObjectResult>(result);
    }

    [Fact]
    public async Task DeleteQuiz_NotOwnerAndNotAdmin_ReturnsForbid()
    {
        // Arrange
        SetupAuthenticatedUser("user123", "User"); // Regular user

        var mockQuiz = new Quiz
        {
            Id = 1,
            UserId = "differentUser", // Different owner
            Title = "Test Quiz",
            Questions = new List<Question>()
        };

        _mockRepo.Setup(repo => repo.GetQuizById(1)).ReturnsAsync(mockQuiz);

        // Act
        var result = await _controller.DeleteQuiz(1);

        // Assert
        Assert.IsType<ForbidResult>(result);
    }

    [Fact]
    public async Task DeleteQuiz_AsOwner_Success()
    {
        // Arrange
        SetupAuthenticatedUser("user123", "User");

        var mockQuiz = new Quiz
        {
            Id = 1,
            UserId = "user123", // Same user
            Title = "Test Quiz",
            Questions = new List<Question>()
        };

        _mockRepo.Setup(repo => repo.GetQuizById(1)).ReturnsAsync(mockQuiz);
        _mockRepo.Setup(repo => repo.DeleteQuiz(1)).ReturnsAsync(true);

        // Act
        var result = await _controller.DeleteQuiz(1);

        // Assert
        Assert.IsType<NoContentResult>(result);
    }
    #endregion
}